nameOverride: ""
fullnameOverride: ""

# The distros and kernel versions to target
# A daemonset will be created for each OS and kernel version that targets
# only nodes with that particular OS and kernel version using labels from
# the node feature discovery addon
# A "catchall" daemonset will also be created for each distro that targets
# nodes running that distro with a kernel version that is not in the list
# In this case, the OFED driver container is able to dynamically recompile
# the OFED driver for the running kernel - it just takes ages (note that
# this is still a distro-specific process, so we cannot use one container
# image for all distros)
distroKernelVersions:
  - id: ubuntu
    version: "20.04"
    kernelVersions:
      - 5.4.0-81-generic
      - 5.4.0-84-generic

image:
  repository: ghcr.io/stackhpc/mofed
  pullPolicy: IfNotPresent

imagePullSecrets: []

podSecurityContext: {}
# We require a privileged container
securityContext:
  privileged: true

nodeSelector:
  archLabel: kubernetes.io/arch
  # Use labels from the node feature discovery addon
  pciDeviceLabel: feature.node.kubernetes.io/pci-15b3.present
  osIdLabel: feature.node.kubernetes.io/system-os_release.ID
  osVersionLabel: feature.node.kubernetes.io/system-os_release.VERSION_ID
  kernelVersionLabel: feature.node.kubernetes.io/kernel-version.full

probes:
  startup:
    initialDelaySeconds: 10
    failureThreshold: 60
    # When a recompilation is required, we need a much bigger failure threshold
    # It can take up to 45m, so allow an hour
    failureThresholdRecompilation: 360
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10

# OFED pods can take a while to exit due to unloading of drivers
terminationGracePeriodSeconds: 120

# Annotations for the daemonset pods
podAnnotations:
  scheduler.alpha.kubernetes.io/critical-pod: ""

# Tolerations for the daemonset pods
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

# Resources for the daemonset pods
resources: {}
