name: Publish artifacts
# Run the tasks on every push
on: push
jobs:
  build_push_ubuntu_image:
    name: Build and push ubuntu image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ofed_version: [5.4-1.0.3.0]
        distro: [ubuntu20.04]
        kernel_version:
          - 5.4.0-81-generic
          - 5.4.0-84-generic
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker layer caching
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.ofed_version }}-${{ matrix.distro }}-${{ matrix.kernel_version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.ofed_version }}-${{ matrix.distro }}-${{ matrix.kernel_version }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            MLNX_OFED_VERSION=${{ matrix.ofed_version }}
            MLNX_OFED_DISTRO=${{ matrix.distro }}
            MLNX_OFED_ARCH=amd64
            MLNX_OFED_KERNEL_VERSION=${{ matrix.kernel_version }}
          push: true
          tags: ghcr.io/stackhpc/mofed:${{ matrix.ofed_version }}-${{ matrix.distro }}-${{ matrix.kernel_version }}-amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      # https://github.com/docker/buildx/pull/535
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
